Feature ETP-887: First implementation of the tasks module
etendosoftware/com.etendoerp.task pull request #1
Opened 2024-12-15 17:35 UTC by jortolanosmf

2024-12-16 13:08 UTC, Matias-Bernal commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--1B39A7116F0A44A28D6D802626C05435-->  <NAME><![CDATA[Etask_Task_ID]]></NAME>
Did you synchronize terminology?

2024-12-16 13:09 UTC, Matias-Bernal commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--32C4A8C0D0384121B9DD865D16214209-->  <DESCRIPTION><![CDATA[Table ID.]]></DESCRIPTION>
What do you mean with this?

2024-12-16 13:11 UTC, Matias-Bernal commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--861E6BDBC102490B8B69DCC6DA1B98E3-->  <DEFAULTVALUE><![CDATA[@SQL=SELECT MAX(AD_MODULE_ID) FROM AD_MODULE WHERE ISDEFAULT='Y']]></DEFAULTVALUE>
also this module must be in development.

2024-12-16 13:11 UTC, Matias-Bernal commented on src-db/database/sourcedata/AD_ELEMENT.xml
> +<!--6192260BFC9043208CED0C2EA4A33475-->  <NAME><![CDATA[Etask_Task_ID]]></NAME>
Fix it

2024-12-16 13:11 UTC, Matias-Bernal commented on src-db/database/sourcedata/AD_ELEMENT.xml
> +<!--C38B94CC49024CF19ED0247FDE35AD5C-->  <DESCRIPTION><![CDATA[Table ID.]]></DESCRIPTION>
Check it

2024-12-16 13:20 UTC, Matias-Bernal requested changes
Fix comments.

2024-12-18 11:19 UTC, ivanrobledofutit approved these changes

2024-12-18 12:32 UTC, merged